### PR TITLE
Update to 1.19

### PR DESCRIPTION
**Pull request by Lemmmy**
Similar to #12, this PR prepares the mod for Minecraft 1.19. It currently targets 1.19-pre5 and Fabric API 0.54, and updates loom to 0.12-SNAPSHOT. I am not expecting any major changes between now and June 7th, so when 1.19 is released, gradle.properties can be bumped and this PR can be merged.

image

### CODE REVIEW

**Comment by arnokeesman** [comment]
I get an error with this version. [logs](https://mclo.gs/gyrtGJ2)

**Comment by arnokeesman** [comment]
Was able to build a working jar using the build task (was using jar before) in IntelliJ IDEA Gradle -> Tasks -> build -> build
Thanks for the clarification.

**Comment by CarbonGhost** [comment]
@lucko can you please review this PR and provide an official 1.19 version of the mod? I asked on the LP Discord, but it doesn't seem that other LuckPerms contributors are able to do anything on this repositories.

**Comment by Lemmmy** [comment]
I know 1.19.1 is possibly round the corner, this PR will be updated to 1.19.1 if it is still open by the time it releases (otherwise I will just make another one)

**Comment by lucko** [comment]
Thanks! :)

**Pull request merged**
